Use feature(const_fn_trait_bound) instead of feature(const_fn)
    error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
      --> examples/const_fn_test/tests/test.rs:11:6
       |
    11 | impl<T: IntoIterator> A<T> {
       |      ^
       |
       = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
       = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable